backend:
  name: git-gateway
  branch: main

media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "produtos"
    label: "Produtos"
    folder: "public/data/produtos"
    create: true
    slug: "{{nome}}"
    fields:
      - { label: "ID", name: "id", widget: "string" }
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Preço", name: "preco", widget: "number", value_type: "float" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Categoria", name: "categoria", widget: "select", options: ["Pastel Salgado", "Pastel Doce", "Bebida"] }
      - { label: "Imagem", name: "imagem", widget: "image" }
